name: Buil-UI_Testing-Deploy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    Build-and-Unit-testing:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the application
              uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install NPM dependencies
              run: npm install
            - name: Execute the Unit tests
              run: npm run test:unit
            - name: Display SoftUni username
              run: echo 'baigeorgi'
